#!/usr/bin/env node
import { readFileSync, writeFileSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const dir = dirname(fileURLToPath(import.meta.url));
const phasesDir = join(dir, 'phases');
const configPath = join(dir, 'phase-config.json');
const today = new Date().toISOString().slice(0, 10);

function die(msg) { process.stderr.write(`ERROR: ${msg}\n`); process.exit(1); }

// Find the next "\n## " that is NOT inside a ``` code fence.
function nextSectionBoundary(text, startIdx) {
  let inFence = false;
  let i = startIdx;
  while (i < text.length) {
    // Check for fence toggle at start of line
    if ((i === 0 || text[i - 1] === '\n') && text.startsWith('```', i)) {
      inFence = !inFence;
      i += 3;
      continue;
    }
    if (!inFence && text.startsWith('\n## ', i)) return i;
    i++;
  }
  return -1;
}

let config;
try { config = JSON.parse(readFileSync(configPath, 'utf8')); }
catch { die(`Cannot read ${configPath}`); }

if (!Array.isArray(config.derived) || config.derived.length === 0)
  die('No derived phases in config');

// Collect all outputs before writing anything (fail closed).
const results = [];

for (const d of config.derived) {
  let base;
  try { base = readFileSync(join(phasesDir, d.base), 'utf8'); }
  catch { die(`Base file not found: ${d.base}`); }

  // Strip original header: everything before the first line starting with "## "
  const bodyStart = base.search(/^## /m);
  if (bodyStart === -1) die(`No ## heading found in ${d.base}`);
  let body = base.slice(bodyStart);

  // Extract base phase number from filename (e.g. "01" from "01-plan-ceo.md")
  const basePhaseNumber = d.base.match(/^(\d+)/)?.[1] ?? '??';

  // Apply section overrides
  for (const [key, replacement] of Object.entries(d.sectionOverrides ?? {})) {
    const heading = `## ${key}\n`;
    const headingIdx = body.indexOf(heading);
    if (headingIdx === -1) die(`Section "## ${key}" not found in ${d.base}`);

    // Section ends at the next "\n## " or end of string
    const afterHeading = headingIdx + heading.length;
    const nextSection = nextSectionBoundary(body, afterHeading);
    const sectionEnd = nextSection === -1 ? body.length : nextSection;

    if (replacement === null) {
      // Remove the entire section (heading + content)
      body = body.slice(0, headingIdx) + body.slice(sectionEnd);
      body = body.replace(/\n{3,}/g, '\n\n');
    } else {
      // Replace the content, keep a fresh heading
      body = body.slice(0, headingIdx) + `## ${key}\n\n${replacement}\n` + body.slice(sectionEnd);
    }
  }

  // Append sections
  if (d.appendSections) body = body.trimEnd() + '\n\n' + d.appendSections + '\n';

  // Extract gstack source info from base phase header
  const baseHeader = base.slice(0, bodyStart);
  const hashMatch = baseHeader.match(/^# Gstack source hash: (.+)$/m);
  const derivedMatch = baseHeader.match(/^# Derived from: (.+)$/m);

  // Build header
  const diffs = (d.differences ?? []).map(s => `# - ${s}`).join('\n');
  const extras = (d.additionalDirectives ?? []).map(s => `# - ${s}`).join('\n');
  const header = [
    `# Phase ${d.phaseNumber}: ${d.title}`,
    `# PATTAYA AUTONOMOUS PHASE — NOT A GSTACK SKILL`,
    `# DERIVED FROM: pipeline/phases/${d.base}`,
    derivedMatch ? `# Also derived from: ${derivedMatch[1]}` : null,
    hashMatch ? `# Gstack source hash: ${hashMatch[1]}` : null,
    `# Generated by: pipeline/gen-phases.mjs`,
    `# Last generated: ${today}`,
    `#`,
    `# DIFFERENCES FROM PHASE ${basePhaseNumber}:`,
    diffs,
    `#`,
    `# DIRECTIVES:`,
    `# - Do NOT invoke /skills or use AskUserQuestion`,
    `# - Write all output to {PHASE_ARTIFACTS}/phase-${d.phaseNumber}-${d.slug}.md`,
    `# - Read prior phase artifacts from disk, not conversation history`,
    `# - Work in output/ directory for generated code`,
    `# - Make ALL decisions autonomously`,
    extras,
  ].filter(Boolean).join('\n');

  const content = header + '\n\n' + body.trimStart();
  results.push({ output: d.output, base: d.base, content });
}

// All good — write everything.
for (const r of results) {
  writeFileSync(join(phasesDir, r.output), r.content);
  console.log(`Generated ${r.output} from ${r.base}`);
}

console.log(`Generated ${results.length} derived phases from ${results.length} base phases`);
